package io.voucherify.client.model.voucher;

public enum DiscountEffect {
  ADD_MISSING_ITEMS,
  ADD_NEW_ITEMS,
  APPLY_TO_ORDER,
  APPLY_TO_ITEMS,
  APPLY_TO_ITEMS_PROPORTIONALLY,
  APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY,
  APPLY_TO_EVERY
}
