/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.voucherify.client.model.LoyaltyPendingPointsDetailsEarningRule;
import io.voucherify.client.model.LoyaltyPendingPointsDetailsEvent;
import io.voucherify.client.model.LoyaltyPendingPointsDetailsHolderLoyaltyTier;
import io.voucherify.client.model.LoyaltyPendingPointsDetailsLoyaltyTier;
import io.voucherify.client.model.LoyaltyPendingPointsDetailsOrder;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * Details about how the pending points were earned.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class LoyaltyPendingPointsDetails {
  public static final String SERIALIZED_NAME_LOYALTY_TIER = "loyalty_tier";
  @SerializedName(SERIALIZED_NAME_LOYALTY_TIER)
  private LoyaltyPendingPointsDetailsLoyaltyTier loyaltyTier;
    private boolean loyaltyTierIsSet = false;

  public static final String SERIALIZED_NAME_HOLDER_LOYALTY_TIER = "holder_loyalty_tier";
  @SerializedName(SERIALIZED_NAME_HOLDER_LOYALTY_TIER)
  private LoyaltyPendingPointsDetailsHolderLoyaltyTier holderLoyaltyTier;
    private boolean holderLoyaltyTierIsSet = false;

  public static final String SERIALIZED_NAME_EVENT = "event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  private LoyaltyPendingPointsDetailsEvent event;
    private boolean eventIsSet = false;

  public static final String SERIALIZED_NAME_EARNING_RULE = "earning_rule";
  @SerializedName(SERIALIZED_NAME_EARNING_RULE)
  private LoyaltyPendingPointsDetailsEarningRule earningRule;
    private boolean earningRuleIsSet = false;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private LoyaltyPendingPointsDetailsOrder order;
    private boolean orderIsSet = false;

  public LoyaltyPendingPointsDetails() {
  }

  public LoyaltyPendingPointsDetails loyaltyTier(LoyaltyPendingPointsDetailsLoyaltyTier loyaltyTier) {
    
    this.loyaltyTier = loyaltyTier;
    return this;
  }

   /**
   * Get loyaltyTier
   * @return loyaltyTier
  **/
  @javax.annotation.Nullable
  public LoyaltyPendingPointsDetailsLoyaltyTier getLoyaltyTier() {
    return loyaltyTier;
  }


  public void setLoyaltyTier(LoyaltyPendingPointsDetailsLoyaltyTier loyaltyTier) {
    this.loyaltyTier = loyaltyTier;
    this.loyaltyTierIsSet = true;
  }
  public boolean isLoyaltyTierSet() {
    return loyaltyTierIsSet;
  }


  public LoyaltyPendingPointsDetails holderLoyaltyTier(LoyaltyPendingPointsDetailsHolderLoyaltyTier holderLoyaltyTier) {
    
    this.holderLoyaltyTier = holderLoyaltyTier;
    return this;
  }

   /**
   * Get holderLoyaltyTier
   * @return holderLoyaltyTier
  **/
  @javax.annotation.Nullable
  public LoyaltyPendingPointsDetailsHolderLoyaltyTier getHolderLoyaltyTier() {
    return holderLoyaltyTier;
  }


  public void setHolderLoyaltyTier(LoyaltyPendingPointsDetailsHolderLoyaltyTier holderLoyaltyTier) {
    this.holderLoyaltyTier = holderLoyaltyTier;
    this.holderLoyaltyTierIsSet = true;
  }
  public boolean isHolderLoyaltyTierSet() {
    return holderLoyaltyTierIsSet;
  }


  public LoyaltyPendingPointsDetails event(LoyaltyPendingPointsDetailsEvent event) {
    
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @javax.annotation.Nullable
  public LoyaltyPendingPointsDetailsEvent getEvent() {
    return event;
  }


  public void setEvent(LoyaltyPendingPointsDetailsEvent event) {
    this.event = event;
    this.eventIsSet = true;
  }
  public boolean isEventSet() {
    return eventIsSet;
  }


  public LoyaltyPendingPointsDetails earningRule(LoyaltyPendingPointsDetailsEarningRule earningRule) {
    
    this.earningRule = earningRule;
    return this;
  }

   /**
   * Get earningRule
   * @return earningRule
  **/
  @javax.annotation.Nullable
  public LoyaltyPendingPointsDetailsEarningRule getEarningRule() {
    return earningRule;
  }


  public void setEarningRule(LoyaltyPendingPointsDetailsEarningRule earningRule) {
    this.earningRule = earningRule;
    this.earningRuleIsSet = true;
  }
  public boolean isEarningRuleSet() {
    return earningRuleIsSet;
  }


  public LoyaltyPendingPointsDetails order(LoyaltyPendingPointsDetailsOrder order) {
    
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @javax.annotation.Nullable
  public LoyaltyPendingPointsDetailsOrder getOrder() {
    return order;
  }


  public void setOrder(LoyaltyPendingPointsDetailsOrder order) {
    this.order = order;
    this.orderIsSet = true;
  }
  public boolean isOrderSet() {
    return orderIsSet;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltyPendingPointsDetails loyaltyPendingPointsDetails = (LoyaltyPendingPointsDetails) o;
    return Objects.equals(this.loyaltyTier, loyaltyPendingPointsDetails.loyaltyTier) &&
        Objects.equals(this.holderLoyaltyTier, loyaltyPendingPointsDetails.holderLoyaltyTier) &&
        Objects.equals(this.event, loyaltyPendingPointsDetails.event) &&
        Objects.equals(this.earningRule, loyaltyPendingPointsDetails.earningRule) &&
        Objects.equals(this.order, loyaltyPendingPointsDetails.order);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(loyaltyTier, holderLoyaltyTier, event, earningRule, order);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyPendingPointsDetails {\n");
    sb.append("    loyaltyTier: ").append(toIndentedString(loyaltyTier)).append("\n");
    sb.append("    holderLoyaltyTier: ").append(toIndentedString(holderLoyaltyTier)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    earningRule: ").append(toIndentedString(earningRule)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("loyalty_tier");
    openapiFields.add("holder_loyalty_tier");
    openapiFields.add("event");
    openapiFields.add("earning_rule");
    openapiFields.add("order");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoyaltyPendingPointsDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoyaltyPendingPointsDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoyaltyPendingPointsDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoyaltyPendingPointsDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<LoyaltyPendingPointsDetails>() {
           @Override
           public void write(JsonWriter out, LoyaltyPendingPointsDetails value) throws IOException {
            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();

            // 1. Strip all nulls and internal "isSet" markers
            obj.entrySet().removeIf(entry -> entry.getValue().isJsonNull() || entry.getKey().endsWith("IsSet"));

            // 2. Add back explicitly set nulls using reflection
            for (Field field : LoyaltyPendingPointsDetails.class.getDeclaredFields()) {
              String fieldName = field.getName();
              if (fieldName.endsWith("IsSet")) continue;
              try {
                Field isSetField = LoyaltyPendingPointsDetails.class.getDeclaredField(fieldName + "IsSet");
                isSetField.setAccessible(true);
                boolean isSet = (boolean) isSetField.get(value);

                field.setAccessible(true);
                Object fieldValue = field.get(value);

                if (isSet && fieldValue == null) {
                  // convert camelCase to snake_case (OpenAPI property names are snake_case)
                  String jsonName = fieldName.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
                  obj.add(jsonName, JsonNull.INSTANCE);
                }
              } catch (NoSuchFieldException ignored) {
                // no isSet marker → skip
              } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
              }
            }

             elementAdapter.write(out, obj);
           }

           @Override
           public LoyaltyPendingPointsDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoyaltyPendingPointsDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoyaltyPendingPointsDetails
  * @throws IOException if the JSON string is invalid with respect to LoyaltyPendingPointsDetails
  */
  public static LoyaltyPendingPointsDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoyaltyPendingPointsDetails.class);
  }

 /**
  * Convert an instance of LoyaltyPendingPointsDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

