/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * A hypothetical order line item used for estimation.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;
    private boolean idIsSet = false;

  public static final String SERIALIZED_NAME_SOURCE_ID = "source_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_ID)
  private String sourceId;
    private boolean sourceIdIsSet = false;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private String productId;
    private boolean productIdIsSet = false;

  public static final String SERIALIZED_NAME_SKU_ID = "sku_id";
  @SerializedName(SERIALIZED_NAME_SKU_ID)
  private String skuId;
    private boolean skuIdIsSet = false;

  public static final String SERIALIZED_NAME_RELATED_OBJECT = "related_object";
  @SerializedName(SERIALIZED_NAME_RELATED_OBJECT)
  private Object relatedObject = null;
    private boolean relatedObjectIsSet = false;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;
    private boolean amountIsSet = false;

  public static final String SERIALIZED_NAME_DISCOUNT_AMOUNT = "discount_amount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_AMOUNT)
  private BigDecimal discountAmount;
    private boolean discountAmountIsSet = false;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private BigDecimal quantity;
    private boolean quantityIsSet = false;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;
    private boolean priceIsSet = false;

  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  private Object product = null;
    private boolean productIsSet = false;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private Object sku = null;
    private boolean skuIsSet = false;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata = null;
    private boolean metadataIsSet = false;

  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem() {
  }

  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem id(String id) {
    
    this.id = id;
    this.idIsSet = true;
    return this;
  }

   /**
   * Order item ID assigned by Voucherify. Can be &#x60;null&#x60;.
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
    this.idIsSet = true;
  }
  public boolean isIdSet() {
    return idIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem sourceId(String sourceId) {
    
    this.sourceId = sourceId;
    this.sourceIdIsSet = true;
    return this;
  }

   /**
   * Order item source ID, e.g. from an external system. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return sourceId
  **/
  @javax.annotation.Nullable
  public String getSourceId() {
    return sourceId;
  }


  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
    this.sourceIdIsSet = true;
  }
  public boolean isSourceIdSet() {
    return sourceIdIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem productId(String productId) {
    
    this.productId = productId;
    this.productIdIsSet = true;
    return this;
  }

   /**
   * Product ID. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return productId
  **/
  @javax.annotation.Nullable
  public String getProductId() {
    return productId;
  }


  public void setProductId(String productId) {
    this.productId = productId;
    this.productIdIsSet = true;
  }
  public boolean isProductIdSet() {
    return productIdIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem skuId(String skuId) {
    
    this.skuId = skuId;
    this.skuIdIsSet = true;
    return this;
  }

   /**
   * SKU ID. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return skuId
  **/
  @javax.annotation.Nullable
  public String getSkuId() {
    return skuId;
  }


  public void setSkuId(String skuId) {
    this.skuId = skuId;
    this.skuIdIsSet = true;
  }
  public boolean isSkuIdSet() {
    return skuIdIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem relatedObject(Object relatedObject) {
    
    this.relatedObject = relatedObject;
    this.relatedObjectIsSet = true;
    return this;
  }

   /**
   * Get relatedObject
   * @return relatedObject
  **/
  @javax.annotation.Nullable
  public Object getRelatedObject() {
    return relatedObject;
  }


  public void setRelatedObject(Object relatedObject) {
    this.relatedObject = relatedObject;
    this.relatedObjectIsSet = true;
  }
  public boolean isRelatedObjectSet() {
    return relatedObjectIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem amount(BigDecimal amount) {
    
    this.amount = amount;
    this.amountIsSet = true;
    return this;
  }

   /**
   * Item amount before discounts - a non-negative integer. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return amount
  **/
  @javax.annotation.Nullable
  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
    this.amountIsSet = true;
  }
  public boolean isAmountSet() {
    return amountIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem discountAmount(BigDecimal discountAmount) {
    
    this.discountAmount = discountAmount;
    this.discountAmountIsSet = true;
    return this;
  }

   /**
   * Item discount amount - a non-negative integer. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return discountAmount
  **/
  @javax.annotation.Nullable
  public BigDecimal getDiscountAmount() {
    return discountAmount;
  }


  public void setDiscountAmount(BigDecimal discountAmount) {
    this.discountAmount = discountAmount;
    this.discountAmountIsSet = true;
  }
  public boolean isDiscountAmountSet() {
    return discountAmountIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    this.quantityIsSet = true;
    return this;
  }

   /**
   * Item quantity - a positive integer. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return quantity
  **/
  @javax.annotation.Nullable
  public BigDecimal getQuantity() {
    return quantity;
  }


  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
    this.quantityIsSet = true;
  }
  public boolean isQuantitySet() {
    return quantityIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem price(BigDecimal price) {
    
    this.price = price;
    this.priceIsSet = true;
    return this;
  }

   /**
   * Item unit price - a non-negative integer. May be provided as a string or a number. Can be &#x60;null&#x60;.
   * @return price
  **/
  @javax.annotation.Nullable
  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
    this.priceIsSet = true;
  }
  public boolean isPriceSet() {
    return priceIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem product(Object product) {
    
    this.product = product;
    this.productIsSet = true;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @javax.annotation.Nullable
  public Object getProduct() {
    return product;
  }


  public void setProduct(Object product) {
    this.product = product;
    this.productIsSet = true;
  }
  public boolean isProductSet() {
    return productIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem sku(Object sku) {
    
    this.sku = sku;
    this.skuIsSet = true;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @javax.annotation.Nullable
  public Object getSku() {
    return sku;
  }


  public void setSku(Object sku) {
    this.sku = sku;
    this.skuIsSet = true;
  }
  public boolean isSkuSet() {
    return skuIsSet;
  }


  public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem metadata(Object metadata) {
    
    this.metadata = metadata;
    this.metadataIsSet = true;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
    this.metadataIsSet = true;
  }
  public boolean isMetadataSet() {
    return metadataIsSet;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem loyaltiesExamineEarningRulesExamineRequestBodyOrderItem = (LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem) o;
    return Objects.equals(this.id, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.id) &&
        Objects.equals(this.sourceId, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.sourceId) &&
        Objects.equals(this.productId, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.productId) &&
        Objects.equals(this.skuId, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.skuId) &&
        Objects.equals(this.relatedObject, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.relatedObject) &&
        Objects.equals(this.amount, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.amount) &&
        Objects.equals(this.discountAmount, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.discountAmount) &&
        Objects.equals(this.quantity, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.quantity) &&
        Objects.equals(this.price, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.price) &&
        Objects.equals(this.product, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.product) &&
        Objects.equals(this.sku, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.sku) &&
        Objects.equals(this.metadata, loyaltiesExamineEarningRulesExamineRequestBodyOrderItem.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceId, productId, skuId, relatedObject, amount, discountAmount, quantity, price, product, sku, metadata);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    skuId: ").append(toIndentedString(skuId)).append("\n");
    sb.append("    relatedObject: ").append(toIndentedString(relatedObject)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("source_id");
    openapiFields.add("product_id");
    openapiFields.add("sku_id");
    openapiFields.add("related_object");
    openapiFields.add("amount");
    openapiFields.add("discount_amount");
    openapiFields.add("quantity");
    openapiFields.add("price");
    openapiFields.add("product");
    openapiFields.add("sku");
    openapiFields.add("metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem.class));

       return (TypeAdapter<T>) new TypeAdapter<LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem>() {
           @Override
           public void write(JsonWriter out, LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem value) throws IOException {
            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();

            // 1. Strip all nulls and internal "isSet" markers
            obj.entrySet().removeIf(entry -> entry.getValue().isJsonNull() || entry.getKey().endsWith("IsSet"));

            // 2. Add back explicitly set nulls using reflection
            for (Field field : LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem.class.getDeclaredFields()) {
              String fieldName = field.getName();
              if (fieldName.endsWith("IsSet")) continue;
              try {
                Field isSetField = LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem.class.getDeclaredField(fieldName + "IsSet");
                isSetField.setAccessible(true);
                boolean isSet = (boolean) isSetField.get(value);

                field.setAccessible(true);
                Object fieldValue = field.get(value);

                if (isSet && fieldValue == null) {
                  // convert camelCase to snake_case (OpenAPI property names are snake_case)
                  String jsonName = fieldName.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
                  obj.add(jsonName, JsonNull.INSTANCE);
                }
              } catch (NoSuchFieldException ignored) {
                // no isSet marker → skip
              } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
              }
            }

             elementAdapter.write(out, obj);
           }

           @Override
           public LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem
  * @throws IOException if the JSON string is invalid with respect to LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem
  */
  public static LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem.class);
  }

 /**
  * Convert an instance of LoyaltiesExamineEarningRulesExamineRequestBodyOrderItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

