/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.voucherify.client.model.Junction;
import io.voucherify.client.model.LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId;
import io.voucherify.client.model.LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * Data filters used to narrow down the data records to be returned in the export.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters {
  public static final String SERIALIZED_NAME_JUNCTION = "junction";
  @SerializedName(SERIALIZED_NAME_JUNCTION)
  private Junction junction;

  public static final String SERIALIZED_NAME_VOUCHER_ID = "voucher_id";
  @SerializedName(SERIALIZED_NAME_VOUCHER_ID)
  private LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId voucherId;
    private boolean voucherIdIsSet = false;

  public static final String SERIALIZED_NAME_CAMPAIGN_ID = "campaign_id";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID)
  private LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId campaignId;
    private boolean campaignIdIsSet = false;

  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters() {
  }

  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters junction(Junction junction) {
    
    this.junction = junction;
    return this;
  }

   /**
   * Get junction
   * @return junction
  **/
  @javax.annotation.Nullable
  public Junction getJunction() {
    return junction;
  }


  public void setJunction(Junction junction) {
    this.junction = junction;
  }


  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters voucherId(LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId voucherId) {
    
    this.voucherId = voucherId;
    return this;
  }

   /**
   * Get voucherId
   * @return voucherId
  **/
  @javax.annotation.Nullable
  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId getVoucherId() {
    return voucherId;
  }


  public void setVoucherId(LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId voucherId) {
    this.voucherId = voucherId;
    this.voucherIdIsSet = true;
  }
  public boolean isVoucherIdSet() {
    return voucherIdIsSet;
  }


  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters campaignId(LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId campaignId) {
    
    this.campaignId = campaignId;
    return this;
  }

   /**
   * Get campaignId
   * @return campaignId
  **/
  @javax.annotation.Nullable
  public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId getCampaignId() {
    return campaignId;
  }


  public void setCampaignId(LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId campaignId) {
    this.campaignId = campaignId;
    this.campaignIdIsSet = true;
  }
  public boolean isCampaignIdSet() {
    return campaignIdIsSet;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters loyaltiesPointsExpirationExportCreateResponseBodyParametersFilters = (LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters) o;
    return Objects.equals(this.junction, loyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.junction) &&
        Objects.equals(this.voucherId, loyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.voucherId) &&
        Objects.equals(this.campaignId, loyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.campaignId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(junction, voucherId, campaignId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters {\n");
    sb.append("    junction: ").append(toIndentedString(junction)).append("\n");
    sb.append("    voucherId: ").append(toIndentedString(voucherId)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("junction");
    openapiFields.add("voucher_id");
    openapiFields.add("campaign_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters>() {
           @Override
           public void write(JsonWriter out, LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters value) throws IOException {
            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();

            // 1. Strip all nulls and internal "isSet" markers
            obj.entrySet().removeIf(entry -> entry.getValue().isJsonNull() || entry.getKey().endsWith("IsSet"));

            // 2. Add back explicitly set nulls using reflection
            for (Field field : LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.class.getDeclaredFields()) {
              String fieldName = field.getName();
              if (fieldName.endsWith("IsSet")) continue;
              try {
                Field isSetField = LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.class.getDeclaredField(fieldName + "IsSet");
                isSetField.setAccessible(true);
                boolean isSet = (boolean) isSetField.get(value);

                field.setAccessible(true);
                Object fieldValue = field.get(value);

                if (isSet && fieldValue == null) {
                  // convert camelCase to snake_case (OpenAPI property names are snake_case)
                  String jsonName = fieldName.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
                  obj.add(jsonName, JsonNull.INSTANCE);
                }
              } catch (NoSuchFieldException ignored) {
                // no isSet marker → skip
              } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
              }
            }

             elementAdapter.write(out, obj);
           }

           @Override
           public LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters
  * @throws IOException if the JSON string is invalid with respect to LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters
  */
  public static LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.class);
  }

 /**
  * Convert an instance of LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

