/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.voucherify.client.model.ManagementProjectsCreateResponseBodyApiUsageNotifications;
import io.voucherify.client.model.ManagementProjectsCreateResponseBodyClientSideKey;
import io.voucherify.client.model.ManagementProjectsCreateResponseBodyServerSideKey;
import io.voucherify.client.model.ManagementProjectsCreateResponseBodyWebhooksCalloutNotifications;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * Response body schema for **POST** &#x60;management/v1/projects&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ManagementProjectsCreateResponseBody {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  private String timezone;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_DIAL_CODE = "dial_code";
  @SerializedName(SERIALIZED_NAME_DIAL_CODE)
  private String dialCode;

  /**
   * The webhook version used in the project.
   */
  @JsonAdapter(WebhookVersionEnum.Adapter.class)
  public enum WebhookVersionEnum {
    V2024_01_01("v2024-01-01");

    private String value;

    WebhookVersionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static WebhookVersionEnum fromValue(String value) {
      for (WebhookVersionEnum b : WebhookVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<WebhookVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final WebhookVersionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public WebhookVersionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return WebhookVersionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_WEBHOOK_VERSION = "webhook_version";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_VERSION)
  private WebhookVersionEnum webhookVersion = WebhookVersionEnum.V2024_01_01;

  public static final String SERIALIZED_NAME_CLIENT_TRUSTED_DOMAINS = "client_trusted_domains";
  @SerializedName(SERIALIZED_NAME_CLIENT_TRUSTED_DOMAINS)
  private List<String> clientTrustedDomains;

  public static final String SERIALIZED_NAME_CLIENT_REDEEM_ENABLED = "client_redeem_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_REDEEM_ENABLED)
  private Boolean clientRedeemEnabled;

  public static final String SERIALIZED_NAME_CLIENT_PUBLISH_ENABLED = "client_publish_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_PUBLISH_ENABLED)
  private Boolean clientPublishEnabled;

  public static final String SERIALIZED_NAME_CLIENT_LIST_VOUCHERS_ENABLED = "client_list_vouchers_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_LIST_VOUCHERS_ENABLED)
  private Boolean clientListVouchersEnabled;

  public static final String SERIALIZED_NAME_CLIENT_CREATE_CUSTOMER_ENABLED = "client_create_customer_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_CREATE_CUSTOMER_ENABLED)
  private Boolean clientCreateCustomerEnabled;

  public static final String SERIALIZED_NAME_CLIENT_LOYALTY_EVENTS_ENABLED = "client_loyalty_events_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_LOYALTY_EVENTS_ENABLED)
  private Boolean clientLoyaltyEventsEnabled;

  public static final String SERIALIZED_NAME_CLIENT_SET_VOUCHER_EXPIRATION_DATE_ENABLED = "client_set_voucher_expiration_date_enabled";
  @SerializedName(SERIALIZED_NAME_CLIENT_SET_VOUCHER_EXPIRATION_DATE_ENABLED)
  private Boolean clientSetVoucherExpirationDateEnabled;

  public static final String SERIALIZED_NAME_API_USAGE_NOTIFICATIONS = "api_usage_notifications";
  @SerializedName(SERIALIZED_NAME_API_USAGE_NOTIFICATIONS)
  private ManagementProjectsCreateResponseBodyApiUsageNotifications apiUsageNotifications;

  public static final String SERIALIZED_NAME_WEBHOOKS_CALLOUT_NOTIFICATIONS = "webhooks_callout_notifications";
  @SerializedName(SERIALIZED_NAME_WEBHOOKS_CALLOUT_NOTIFICATIONS)
  private ManagementProjectsCreateResponseBodyWebhooksCalloutNotifications webhooksCalloutNotifications;

  public static final String SERIALIZED_NAME_CLUSTER_ID = "cluster_id";
  @SerializedName(SERIALIZED_NAME_CLUSTER_ID)
  private String clusterId;

  public static final String SERIALIZED_NAME_CASE_SENSITIVE_CODES = "case_sensitive_codes";
  @SerializedName(SERIALIZED_NAME_CASE_SENSITIVE_CODES)
  private Boolean caseSensitiveCodes;

  /**
   * The API version used in the project. Currently, the default and only value is &#x60;v2018-08-01&#x60;.
   */
  @JsonAdapter(ApiVersionEnum.Adapter.class)
  public enum ApiVersionEnum {
    V2018_08_01("v2018-08-01");

    private String value;

    ApiVersionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ApiVersionEnum fromValue(String value) {
      for (ApiVersionEnum b : ApiVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<ApiVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ApiVersionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ApiVersionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ApiVersionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_API_VERSION = "api_version";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private ApiVersionEnum apiVersion = ApiVersionEnum.V2018_08_01;

  public static final String SERIALIZED_NAME_IS_SANDBOX = "is_sandbox";
  @SerializedName(SERIALIZED_NAME_IS_SANDBOX)
  private Boolean isSandbox;

  public static final String SERIALIZED_NAME_WEBHOOK_TOKEN = "webhook_token";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_TOKEN)
  private String webhookToken;

  public static final String SERIALIZED_NAME_SERVER_SIDE_KEY = "server_side_key";
  @SerializedName(SERIALIZED_NAME_SERVER_SIDE_KEY)
  private ManagementProjectsCreateResponseBodyServerSideKey serverSideKey;

  public static final String SERIALIZED_NAME_CLIENT_SIDE_KEY = "client_side_key";
  @SerializedName(SERIALIZED_NAME_CLIENT_SIDE_KEY)
  private ManagementProjectsCreateResponseBodyClientSideKey clientSideKey;

  public ManagementProjectsCreateResponseBody() {
  }

  public ManagementProjectsCreateResponseBody id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the project.
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ManagementProjectsCreateResponseBody name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the project.
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ManagementProjectsCreateResponseBody description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A user-defined description of the project, e.g. its purpose, scope, region.
   * @return description
  **/
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ManagementProjectsCreateResponseBody timezone(String timezone) {
    
    this.timezone = timezone;
    return this;
  }

   /**
   * The time zone in which the project is established. It can be in the GMT format or in accordance with IANA time zone database.
   * @return timezone
  **/
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }


  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  public ManagementProjectsCreateResponseBody currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * The currency used in the project. It is equal to a 3-letter ISO 4217 code.
   * @return currency
  **/
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public ManagementProjectsCreateResponseBody dialCode(String dialCode) {
    
    this.dialCode = dialCode;
    return this;
  }

   /**
   * The country dial code for the project. It is equal to an ITU country code.
   * @return dialCode
  **/
  @javax.annotation.Nullable
  public String getDialCode() {
    return dialCode;
  }


  public void setDialCode(String dialCode) {
    this.dialCode = dialCode;
  }


  public ManagementProjectsCreateResponseBody webhookVersion(WebhookVersionEnum webhookVersion) {
    
    this.webhookVersion = webhookVersion;
    return this;
  }

   /**
   * The webhook version used in the project.
   * @return webhookVersion
  **/
  @javax.annotation.Nullable
  public WebhookVersionEnum getWebhookVersion() {
    return webhookVersion;
  }


  public void setWebhookVersion(WebhookVersionEnum webhookVersion) {
    this.webhookVersion = webhookVersion;
  }


  public ManagementProjectsCreateResponseBody clientTrustedDomains(List<String> clientTrustedDomains) {
    
    this.clientTrustedDomains = clientTrustedDomains;
    return this;
  }

  public ManagementProjectsCreateResponseBody addClientTrustedDomainsItem(String clientTrustedDomainsItem) {
    if (this.clientTrustedDomains == null) {
      this.clientTrustedDomains = new ArrayList<>();
    }
    this.clientTrustedDomains.add(clientTrustedDomainsItem);
    return this;
  }

   /**
   * An array of URL addresses that allow client requests.
   * @return clientTrustedDomains
  **/
  @javax.annotation.Nullable
  public List<String> getClientTrustedDomains() {
    return clientTrustedDomains;
  }


  public void setClientTrustedDomains(List<String> clientTrustedDomains) {
    this.clientTrustedDomains = clientTrustedDomains;
  }


  public ManagementProjectsCreateResponseBody clientRedeemEnabled(Boolean clientRedeemEnabled) {
    
    this.clientRedeemEnabled = clientRedeemEnabled;
    return this;
  }

   /**
   * Enables client-side redemption.
   * @return clientRedeemEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientRedeemEnabled() {
    return clientRedeemEnabled;
  }


  public void setClientRedeemEnabled(Boolean clientRedeemEnabled) {
    this.clientRedeemEnabled = clientRedeemEnabled;
  }


  public ManagementProjectsCreateResponseBody clientPublishEnabled(Boolean clientPublishEnabled) {
    
    this.clientPublishEnabled = clientPublishEnabled;
    return this;
  }

   /**
   * Enables client-side publication.
   * @return clientPublishEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientPublishEnabled() {
    return clientPublishEnabled;
  }


  public void setClientPublishEnabled(Boolean clientPublishEnabled) {
    this.clientPublishEnabled = clientPublishEnabled;
  }


  public ManagementProjectsCreateResponseBody clientListVouchersEnabled(Boolean clientListVouchersEnabled) {
    
    this.clientListVouchersEnabled = clientListVouchersEnabled;
    return this;
  }

   /**
   * Enables client-side listing of vouchers.
   * @return clientListVouchersEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientListVouchersEnabled() {
    return clientListVouchersEnabled;
  }


  public void setClientListVouchersEnabled(Boolean clientListVouchersEnabled) {
    this.clientListVouchersEnabled = clientListVouchersEnabled;
  }


  public ManagementProjectsCreateResponseBody clientCreateCustomerEnabled(Boolean clientCreateCustomerEnabled) {
    
    this.clientCreateCustomerEnabled = clientCreateCustomerEnabled;
    return this;
  }

   /**
   * Enables client-side creation of customers.
   * @return clientCreateCustomerEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientCreateCustomerEnabled() {
    return clientCreateCustomerEnabled;
  }


  public void setClientCreateCustomerEnabled(Boolean clientCreateCustomerEnabled) {
    this.clientCreateCustomerEnabled = clientCreateCustomerEnabled;
  }


  public ManagementProjectsCreateResponseBody clientLoyaltyEventsEnabled(Boolean clientLoyaltyEventsEnabled) {
    
    this.clientLoyaltyEventsEnabled = clientLoyaltyEventsEnabled;
    return this;
  }

   /**
   * Enables client-side events for loyalty and referral programs.
   * @return clientLoyaltyEventsEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientLoyaltyEventsEnabled() {
    return clientLoyaltyEventsEnabled;
  }


  public void setClientLoyaltyEventsEnabled(Boolean clientLoyaltyEventsEnabled) {
    this.clientLoyaltyEventsEnabled = clientLoyaltyEventsEnabled;
  }


  public ManagementProjectsCreateResponseBody clientSetVoucherExpirationDateEnabled(Boolean clientSetVoucherExpirationDateEnabled) {
    
    this.clientSetVoucherExpirationDateEnabled = clientSetVoucherExpirationDateEnabled;
    return this;
  }

   /**
   * Enables client-side setting of voucher expiration date.
   * @return clientSetVoucherExpirationDateEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getClientSetVoucherExpirationDateEnabled() {
    return clientSetVoucherExpirationDateEnabled;
  }


  public void setClientSetVoucherExpirationDateEnabled(Boolean clientSetVoucherExpirationDateEnabled) {
    this.clientSetVoucherExpirationDateEnabled = clientSetVoucherExpirationDateEnabled;
  }


  public ManagementProjectsCreateResponseBody apiUsageNotifications(ManagementProjectsCreateResponseBodyApiUsageNotifications apiUsageNotifications) {
    
    this.apiUsageNotifications = apiUsageNotifications;
    return this;
  }

   /**
   * Get apiUsageNotifications
   * @return apiUsageNotifications
  **/
  @javax.annotation.Nullable
  public ManagementProjectsCreateResponseBodyApiUsageNotifications getApiUsageNotifications() {
    return apiUsageNotifications;
  }


  public void setApiUsageNotifications(ManagementProjectsCreateResponseBodyApiUsageNotifications apiUsageNotifications) {
    this.apiUsageNotifications = apiUsageNotifications;
  }


  public ManagementProjectsCreateResponseBody webhooksCalloutNotifications(ManagementProjectsCreateResponseBodyWebhooksCalloutNotifications webhooksCalloutNotifications) {
    
    this.webhooksCalloutNotifications = webhooksCalloutNotifications;
    return this;
  }

   /**
   * Get webhooksCalloutNotifications
   * @return webhooksCalloutNotifications
  **/
  @javax.annotation.Nullable
  public ManagementProjectsCreateResponseBodyWebhooksCalloutNotifications getWebhooksCalloutNotifications() {
    return webhooksCalloutNotifications;
  }


  public void setWebhooksCalloutNotifications(ManagementProjectsCreateResponseBodyWebhooksCalloutNotifications webhooksCalloutNotifications) {
    this.webhooksCalloutNotifications = webhooksCalloutNotifications;
  }


  public ManagementProjectsCreateResponseBody clusterId(String clusterId) {
    
    this.clusterId = clusterId;
    return this;
  }

   /**
   * The identifier of the cluster where the project will be created.
   * @return clusterId
  **/
  @javax.annotation.Nullable
  public String getClusterId() {
    return clusterId;
  }


  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }


  public ManagementProjectsCreateResponseBody caseSensitiveCodes(Boolean caseSensitiveCodes) {
    
    this.caseSensitiveCodes = caseSensitiveCodes;
    return this;
  }

   /**
   * Determines if the vouchers in the project will be: - case sensitive - if &#x60;true&#x60;, &#x60;C0dE-cfV&#x60; is **not** equal to &#x60;c0de-cfv&#x60;), - case insensitive - if &#x60;false&#x60;, &#x60;C0dE-cfV&#x60; is equal to &#x60;c0de-cfv&#x60;.
   * @return caseSensitiveCodes
  **/
  @javax.annotation.Nullable
  public Boolean getCaseSensitiveCodes() {
    return caseSensitiveCodes;
  }


  public void setCaseSensitiveCodes(Boolean caseSensitiveCodes) {
    this.caseSensitiveCodes = caseSensitiveCodes;
  }


  public ManagementProjectsCreateResponseBody apiVersion(ApiVersionEnum apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * The API version used in the project. Currently, the default and only value is &#x60;v2018-08-01&#x60;.
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  public ApiVersionEnum getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(ApiVersionEnum apiVersion) {
    this.apiVersion = apiVersion;
  }


  public ManagementProjectsCreateResponseBody isSandbox(Boolean isSandbox) {
    
    this.isSandbox = isSandbox;
    return this;
  }

   /**
   * Determines if the project is a sandbox project.
   * @return isSandbox
  **/
  @javax.annotation.Nullable
  public Boolean getIsSandbox() {
    return isSandbox;
  }


  public void setIsSandbox(Boolean isSandbox) {
    this.isSandbox = isSandbox;
  }


  public ManagementProjectsCreateResponseBody webhookToken(String webhookToken) {
    
    this.webhookToken = webhookToken;
    return this;
  }

   /**
   * Webhook token used for authentication.
   * @return webhookToken
  **/
  @javax.annotation.Nullable
  public String getWebhookToken() {
    return webhookToken;
  }


  public void setWebhookToken(String webhookToken) {
    this.webhookToken = webhookToken;
  }


  public ManagementProjectsCreateResponseBody serverSideKey(ManagementProjectsCreateResponseBodyServerSideKey serverSideKey) {
    
    this.serverSideKey = serverSideKey;
    return this;
  }

   /**
   * Get serverSideKey
   * @return serverSideKey
  **/
  @javax.annotation.Nullable
  public ManagementProjectsCreateResponseBodyServerSideKey getServerSideKey() {
    return serverSideKey;
  }


  public void setServerSideKey(ManagementProjectsCreateResponseBodyServerSideKey serverSideKey) {
    this.serverSideKey = serverSideKey;
  }


  public ManagementProjectsCreateResponseBody clientSideKey(ManagementProjectsCreateResponseBodyClientSideKey clientSideKey) {
    
    this.clientSideKey = clientSideKey;
    return this;
  }

   /**
   * Get clientSideKey
   * @return clientSideKey
  **/
  @javax.annotation.Nullable
  public ManagementProjectsCreateResponseBodyClientSideKey getClientSideKey() {
    return clientSideKey;
  }


  public void setClientSideKey(ManagementProjectsCreateResponseBodyClientSideKey clientSideKey) {
    this.clientSideKey = clientSideKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagementProjectsCreateResponseBody managementProjectsCreateResponseBody = (ManagementProjectsCreateResponseBody) o;
    return Objects.equals(this.id, managementProjectsCreateResponseBody.id) &&
        Objects.equals(this.name, managementProjectsCreateResponseBody.name) &&
        Objects.equals(this.description, managementProjectsCreateResponseBody.description) &&
        Objects.equals(this.timezone, managementProjectsCreateResponseBody.timezone) &&
        Objects.equals(this.currency, managementProjectsCreateResponseBody.currency) &&
        Objects.equals(this.dialCode, managementProjectsCreateResponseBody.dialCode) &&
        Objects.equals(this.webhookVersion, managementProjectsCreateResponseBody.webhookVersion) &&
        Objects.equals(this.clientTrustedDomains, managementProjectsCreateResponseBody.clientTrustedDomains) &&
        Objects.equals(this.clientRedeemEnabled, managementProjectsCreateResponseBody.clientRedeemEnabled) &&
        Objects.equals(this.clientPublishEnabled, managementProjectsCreateResponseBody.clientPublishEnabled) &&
        Objects.equals(this.clientListVouchersEnabled, managementProjectsCreateResponseBody.clientListVouchersEnabled) &&
        Objects.equals(this.clientCreateCustomerEnabled, managementProjectsCreateResponseBody.clientCreateCustomerEnabled) &&
        Objects.equals(this.clientLoyaltyEventsEnabled, managementProjectsCreateResponseBody.clientLoyaltyEventsEnabled) &&
        Objects.equals(this.clientSetVoucherExpirationDateEnabled, managementProjectsCreateResponseBody.clientSetVoucherExpirationDateEnabled) &&
        Objects.equals(this.apiUsageNotifications, managementProjectsCreateResponseBody.apiUsageNotifications) &&
        Objects.equals(this.webhooksCalloutNotifications, managementProjectsCreateResponseBody.webhooksCalloutNotifications) &&
        Objects.equals(this.clusterId, managementProjectsCreateResponseBody.clusterId) &&
        Objects.equals(this.caseSensitiveCodes, managementProjectsCreateResponseBody.caseSensitiveCodes) &&
        Objects.equals(this.apiVersion, managementProjectsCreateResponseBody.apiVersion) &&
        Objects.equals(this.isSandbox, managementProjectsCreateResponseBody.isSandbox) &&
        Objects.equals(this.webhookToken, managementProjectsCreateResponseBody.webhookToken) &&
        Objects.equals(this.serverSideKey, managementProjectsCreateResponseBody.serverSideKey) &&
        Objects.equals(this.clientSideKey, managementProjectsCreateResponseBody.clientSideKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, timezone, currency, dialCode, webhookVersion, clientTrustedDomains, clientRedeemEnabled, clientPublishEnabled, clientListVouchersEnabled, clientCreateCustomerEnabled, clientLoyaltyEventsEnabled, clientSetVoucherExpirationDateEnabled, apiUsageNotifications, webhooksCalloutNotifications, clusterId, caseSensitiveCodes, apiVersion, isSandbox, webhookToken, serverSideKey, clientSideKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagementProjectsCreateResponseBody {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    dialCode: ").append(toIndentedString(dialCode)).append("\n");
    sb.append("    webhookVersion: ").append(toIndentedString(webhookVersion)).append("\n");
    sb.append("    clientTrustedDomains: ").append(toIndentedString(clientTrustedDomains)).append("\n");
    sb.append("    clientRedeemEnabled: ").append(toIndentedString(clientRedeemEnabled)).append("\n");
    sb.append("    clientPublishEnabled: ").append(toIndentedString(clientPublishEnabled)).append("\n");
    sb.append("    clientListVouchersEnabled: ").append(toIndentedString(clientListVouchersEnabled)).append("\n");
    sb.append("    clientCreateCustomerEnabled: ").append(toIndentedString(clientCreateCustomerEnabled)).append("\n");
    sb.append("    clientLoyaltyEventsEnabled: ").append(toIndentedString(clientLoyaltyEventsEnabled)).append("\n");
    sb.append("    clientSetVoucherExpirationDateEnabled: ").append(toIndentedString(clientSetVoucherExpirationDateEnabled)).append("\n");
    sb.append("    apiUsageNotifications: ").append(toIndentedString(apiUsageNotifications)).append("\n");
    sb.append("    webhooksCalloutNotifications: ").append(toIndentedString(webhooksCalloutNotifications)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    caseSensitiveCodes: ").append(toIndentedString(caseSensitiveCodes)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    isSandbox: ").append(toIndentedString(isSandbox)).append("\n");
    sb.append("    webhookToken: ").append(toIndentedString(webhookToken)).append("\n");
    sb.append("    serverSideKey: ").append(toIndentedString(serverSideKey)).append("\n");
    sb.append("    clientSideKey: ").append(toIndentedString(clientSideKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("timezone");
    openapiFields.add("currency");
    openapiFields.add("dial_code");
    openapiFields.add("webhook_version");
    openapiFields.add("client_trusted_domains");
    openapiFields.add("client_redeem_enabled");
    openapiFields.add("client_publish_enabled");
    openapiFields.add("client_list_vouchers_enabled");
    openapiFields.add("client_create_customer_enabled");
    openapiFields.add("client_loyalty_events_enabled");
    openapiFields.add("client_set_voucher_expiration_date_enabled");
    openapiFields.add("api_usage_notifications");
    openapiFields.add("webhooks_callout_notifications");
    openapiFields.add("cluster_id");
    openapiFields.add("case_sensitive_codes");
    openapiFields.add("api_version");
    openapiFields.add("is_sandbox");
    openapiFields.add("webhook_token");
    openapiFields.add("server_side_key");
    openapiFields.add("client_side_key");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ManagementProjectsCreateResponseBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ManagementProjectsCreateResponseBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ManagementProjectsCreateResponseBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ManagementProjectsCreateResponseBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ManagementProjectsCreateResponseBody>() {
           @Override
           public void write(JsonWriter out, ManagementProjectsCreateResponseBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ManagementProjectsCreateResponseBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ManagementProjectsCreateResponseBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ManagementProjectsCreateResponseBody
  * @throws IOException if the JSON string is invalid with respect to ManagementProjectsCreateResponseBody
  */
  public static ManagementProjectsCreateResponseBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ManagementProjectsCreateResponseBody.class);
  }

 /**
  * Convert an instance of ManagementProjectsCreateResponseBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

