/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * Data conditions used to narrow down the data records to be returned in the result.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ParameterFiltersListCampaignsCampaignStatusConditions {
  /**
   * Gets or Sets $in
   */
  @JsonAdapter(InEnum.Adapter.class)
  public enum InEnum {
    DONE("DONE"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    FAILED("FAILED"),
    
    DRAFT("DRAFT"),
    
    MODIFYING("MODIFYING");

    private String value;

    InEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InEnum fromValue(String value) {
      for (InEnum b : InEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<InEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return InEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_$_IN = "$in";
  @SerializedName(SERIALIZED_NAME_$_IN)
  private List<InEnum> $in;
    private boolean $inIsSet = false;

  /**
   * Gets or Sets $notIn
   */
  @JsonAdapter(NotInEnum.Adapter.class)
  public enum NotInEnum {
    DONE("DONE"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    FAILED("FAILED"),
    
    DRAFT("DRAFT"),
    
    MODIFYING("MODIFYING");

    private String value;

    NotInEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NotInEnum fromValue(String value) {
      for (NotInEnum b : NotInEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<NotInEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NotInEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NotInEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NotInEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_$_NOT_IN = "$not_in";
  @SerializedName(SERIALIZED_NAME_$_NOT_IN)
  private List<NotInEnum> $notIn;
    private boolean $notInIsSet = false;

  /**
   * Value is exactly this value (single value).
   */
  @JsonAdapter(IsEnum.Adapter.class)
  public enum IsEnum {
    DONE("DONE"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    FAILED("FAILED"),
    
    DRAFT("DRAFT"),
    
    MODIFYING("MODIFYING");

    private String value;

    IsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IsEnum fromValue(String value) {
      for (IsEnum b : IsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<IsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_$_IS = "$is";
  @SerializedName(SERIALIZED_NAME_$_IS)
  private IsEnum $is;
    private boolean $isIsSet = false;

  /**
   * Results omit this value (single value).
   */
  @JsonAdapter(IsNotEnum.Adapter.class)
  public enum IsNotEnum {
    DONE("DONE"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    FAILED("FAILED"),
    
    DRAFT("DRAFT"),
    
    MODIFYING("MODIFYING");

    private String value;

    IsNotEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IsNotEnum fromValue(String value) {
      for (IsNotEnum b : IsNotEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
        return null;
    }

    public static class Adapter extends TypeAdapter<IsNotEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IsNotEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IsNotEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IsNotEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_$_IS_NOT = "$is_not";
  @SerializedName(SERIALIZED_NAME_$_IS_NOT)
  private IsNotEnum $isNot;
    private boolean $isNotIsSet = false;

  public static final String SERIALIZED_NAME_$_HAS_VALUE = "$has_value";
  @SerializedName(SERIALIZED_NAME_$_HAS_VALUE)
  private String $hasValue;
    private boolean $hasValueIsSet = false;

  public static final String SERIALIZED_NAME_$_IS_UNKNOWN = "$is_unknown";
  @SerializedName(SERIALIZED_NAME_$_IS_UNKNOWN)
  private String $isUnknown;
    private boolean $isUnknownIsSet = false;

  public static final String SERIALIZED_NAME_$_STARTS_WITH = "$starts_with";
  @SerializedName(SERIALIZED_NAME_$_STARTS_WITH)
  private String $startsWith;
    private boolean $startsWithIsSet = false;

  public static final String SERIALIZED_NAME_$_ENDS_WITH = "$ends_with";
  @SerializedName(SERIALIZED_NAME_$_ENDS_WITH)
  private String $endsWith;
    private boolean $endsWithIsSet = false;

  public ParameterFiltersListCampaignsCampaignStatusConditions() {
  }

  public ParameterFiltersListCampaignsCampaignStatusConditions $in(List<InEnum> $in) {
    
    this.$in = $in;
    return this;
  }

  public ParameterFiltersListCampaignsCampaignStatusConditions add$InItem(InEnum $inItem) {
    if (this.$in == null) {
      this.$in = new ArrayList<>();
    }
    this.$in.add($inItem);
    return this;
  }

   /**
   * Array of resource values that should be included in the results (multiple values).
   * @return $in
  **/
  @javax.annotation.Nullable
  public List<InEnum> get$In() {
    return $in;
  }


  public void set$In(List<InEnum> $in) {
    this.$in = $in;
    this.$inIsSet = true;
  }
  public boolean is$InSet() {
    return $inIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $notIn(List<NotInEnum> $notIn) {
    
    this.$notIn = $notIn;
    return this;
  }

  public ParameterFiltersListCampaignsCampaignStatusConditions add$NotInItem(NotInEnum $notInItem) {
    if (this.$notIn == null) {
      this.$notIn = new ArrayList<>();
    }
    this.$notIn.add($notInItem);
    return this;
  }

   /**
   * Array of resource values that should be included in the results (multiple values).
   * @return $notIn
  **/
  @javax.annotation.Nullable
  public List<NotInEnum> get$NotIn() {
    return $notIn;
  }


  public void set$NotIn(List<NotInEnum> $notIn) {
    this.$notIn = $notIn;
    this.$notInIsSet = true;
  }
  public boolean is$NotInSet() {
    return $notInIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $is(IsEnum $is) {
    
    this.$is = $is;
    return this;
  }

   /**
   * Value is exactly this value (single value).
   * @return $is
  **/
  @javax.annotation.Nullable
  public IsEnum get$Is() {
    return $is;
  }


  public void set$Is(IsEnum $is) {
    this.$is = $is;
    this.$isIsSet = true;
  }
  public boolean is$IsSet() {
    return $isIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $isNot(IsNotEnum $isNot) {
    
    this.$isNot = $isNot;
    return this;
  }

   /**
   * Results omit this value (single value).
   * @return $isNot
  **/
  @javax.annotation.Nullable
  public IsNotEnum get$IsNot() {
    return $isNot;
  }


  public void set$IsNot(IsNotEnum $isNot) {
    this.$isNot = $isNot;
    this.$isNotIsSet = true;
  }
  public boolean is$IsNotSet() {
    return $isNotIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $hasValue(String $hasValue) {
    
    this.$hasValue = $hasValue;
    return this;
  }

   /**
   * Value is NOT null. The value for this parameter is an empty string.
   * @return $hasValue
  **/
  @javax.annotation.Nullable
  public String get$HasValue() {
    return $hasValue;
  }


  public void set$HasValue(String $hasValue) {
    this.$hasValue = $hasValue;
    this.$hasValueIsSet = true;
  }
  public boolean is$HasValueSet() {
    return $hasValueIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $isUnknown(String $isUnknown) {
    
    this.$isUnknown = $isUnknown;
    return this;
  }

   /**
   * Value is null. The value for this parameter is an empty string.
   * @return $isUnknown
  **/
  @javax.annotation.Nullable
  public String get$IsUnknown() {
    return $isUnknown;
  }


  public void set$IsUnknown(String $isUnknown) {
    this.$isUnknown = $isUnknown;
    this.$isUnknownIsSet = true;
  }
  public boolean is$IsUnknownSet() {
    return $isUnknownIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $startsWith(String $startsWith) {
    
    this.$startsWith = $startsWith;
    return this;
  }

   /**
   * Value starts with the specified string.
   * @return $startsWith
  **/
  @javax.annotation.Nullable
  public String get$StartsWith() {
    return $startsWith;
  }


  public void set$StartsWith(String $startsWith) {
    this.$startsWith = $startsWith;
    this.$startsWithIsSet = true;
  }
  public boolean is$StartsWithSet() {
    return $startsWithIsSet;
  }


  public ParameterFiltersListCampaignsCampaignStatusConditions $endsWith(String $endsWith) {
    
    this.$endsWith = $endsWith;
    return this;
  }

   /**
   * Value ends with the specified string.
   * @return $endsWith
  **/
  @javax.annotation.Nullable
  public String get$EndsWith() {
    return $endsWith;
  }


  public void set$EndsWith(String $endsWith) {
    this.$endsWith = $endsWith;
    this.$endsWithIsSet = true;
  }
  public boolean is$EndsWithSet() {
    return $endsWithIsSet;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterFiltersListCampaignsCampaignStatusConditions parameterFiltersListCampaignsCampaignStatusConditions = (ParameterFiltersListCampaignsCampaignStatusConditions) o;
    return Objects.equals(this.$in, parameterFiltersListCampaignsCampaignStatusConditions.$in) &&
        Objects.equals(this.$notIn, parameterFiltersListCampaignsCampaignStatusConditions.$notIn) &&
        Objects.equals(this.$is, parameterFiltersListCampaignsCampaignStatusConditions.$is) &&
        Objects.equals(this.$isNot, parameterFiltersListCampaignsCampaignStatusConditions.$isNot) &&
        Objects.equals(this.$hasValue, parameterFiltersListCampaignsCampaignStatusConditions.$hasValue) &&
        Objects.equals(this.$isUnknown, parameterFiltersListCampaignsCampaignStatusConditions.$isUnknown) &&
        Objects.equals(this.$startsWith, parameterFiltersListCampaignsCampaignStatusConditions.$startsWith) &&
        Objects.equals(this.$endsWith, parameterFiltersListCampaignsCampaignStatusConditions.$endsWith);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash($in, $notIn, $is, $isNot, $hasValue, $isUnknown, $startsWith, $endsWith);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterFiltersListCampaignsCampaignStatusConditions {\n");
    sb.append("    $in: ").append(toIndentedString($in)).append("\n");
    sb.append("    $notIn: ").append(toIndentedString($notIn)).append("\n");
    sb.append("    $is: ").append(toIndentedString($is)).append("\n");
    sb.append("    $isNot: ").append(toIndentedString($isNot)).append("\n");
    sb.append("    $hasValue: ").append(toIndentedString($hasValue)).append("\n");
    sb.append("    $isUnknown: ").append(toIndentedString($isUnknown)).append("\n");
    sb.append("    $startsWith: ").append(toIndentedString($startsWith)).append("\n");
    sb.append("    $endsWith: ").append(toIndentedString($endsWith)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("$in");
    openapiFields.add("$not_in");
    openapiFields.add("$is");
    openapiFields.add("$is_not");
    openapiFields.add("$has_value");
    openapiFields.add("$is_unknown");
    openapiFields.add("$starts_with");
    openapiFields.add("$ends_with");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ParameterFiltersListCampaignsCampaignStatusConditions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ParameterFiltersListCampaignsCampaignStatusConditions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ParameterFiltersListCampaignsCampaignStatusConditions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ParameterFiltersListCampaignsCampaignStatusConditions.class));

       return (TypeAdapter<T>) new TypeAdapter<ParameterFiltersListCampaignsCampaignStatusConditions>() {
           @Override
           public void write(JsonWriter out, ParameterFiltersListCampaignsCampaignStatusConditions value) throws IOException {
            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();

            // 1. Strip all nulls and internal "isSet" markers
            obj.entrySet().removeIf(entry -> entry.getValue().isJsonNull() || entry.getKey().endsWith("IsSet"));

            // 2. Add back explicitly set nulls using reflection
            for (Field field : ParameterFiltersListCampaignsCampaignStatusConditions.class.getDeclaredFields()) {
              String fieldName = field.getName();
              if (fieldName.endsWith("IsSet")) continue;
              try {
                Field isSetField = ParameterFiltersListCampaignsCampaignStatusConditions.class.getDeclaredField(fieldName + "IsSet");
                isSetField.setAccessible(true);
                boolean isSet = (boolean) isSetField.get(value);

                field.setAccessible(true);
                Object fieldValue = field.get(value);

                if (isSet && fieldValue == null) {
                  // convert camelCase to snake_case (OpenAPI property names are snake_case)
                  String jsonName = fieldName.replaceAll("([a-z])([A-Z]+)", "$1_$2").toLowerCase();
                  obj.add(jsonName, JsonNull.INSTANCE);
                }
              } catch (NoSuchFieldException ignored) {
                // no isSet marker → skip
              } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
              }
            }

             elementAdapter.write(out, obj);
           }

           @Override
           public ParameterFiltersListCampaignsCampaignStatusConditions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ParameterFiltersListCampaignsCampaignStatusConditions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ParameterFiltersListCampaignsCampaignStatusConditions
  * @throws IOException if the JSON string is invalid with respect to ParameterFiltersListCampaignsCampaignStatusConditions
  */
  public static ParameterFiltersListCampaignsCampaignStatusConditions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ParameterFiltersListCampaignsCampaignStatusConditions.class);
  }

 /**
  * Convert an instance of ParameterFiltersListCampaignsCampaignStatusConditions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

