/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.voucherify.client.model.Junction;
import io.voucherify.client.model.ParameterFiltersListCampaignsCampaignStatus;
import io.voucherify.client.model.ParameterFiltersListCampaignsCategories;
import io.voucherify.client.model.ParameterFiltersListCampaignsCategoryIds;
import io.voucherify.client.model.ParameterFiltersListCampaignsIsReferralCode;
import io.voucherify.client.model.ParameterFiltersListCampaignsValidityTimeframe;
import io.voucherify.client.model.ParameterFiltersListCampaignsVoucherType;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.voucherify.client.JSON;

/**
 * ParameterFiltersListCampaigns
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ParameterFiltersListCampaigns {
  public static final String SERIALIZED_NAME_CAMPAIGN_STATUS = "campaign_status";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_STATUS)
  private ParameterFiltersListCampaignsCampaignStatus campaignStatus;

  public static final String SERIALIZED_NAME_IS_REFERRAL_CODE = "is_referral_code";
  @SerializedName(SERIALIZED_NAME_IS_REFERRAL_CODE)
  private ParameterFiltersListCampaignsIsReferralCode isReferralCode;

  public static final String SERIALIZED_NAME_VALIDITY_TIMEFRAME = "validity_timeframe";
  @SerializedName(SERIALIZED_NAME_VALIDITY_TIMEFRAME)
  private ParameterFiltersListCampaignsValidityTimeframe validityTimeframe;

  public static final String SERIALIZED_NAME_VOUCHER_TYPE = "voucher_type";
  @SerializedName(SERIALIZED_NAME_VOUCHER_TYPE)
  private ParameterFiltersListCampaignsVoucherType voucherType;

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private ParameterFiltersListCampaignsCategories categories;

  public static final String SERIALIZED_NAME_CATEGORY_IDS = "category_ids";
  @SerializedName(SERIALIZED_NAME_CATEGORY_IDS)
  private ParameterFiltersListCampaignsCategoryIds categoryIds;

  public static final String SERIALIZED_NAME_JUNCTION = "junction";
  @SerializedName(SERIALIZED_NAME_JUNCTION)
  private Junction junction;

  public ParameterFiltersListCampaigns() {
  }

  public ParameterFiltersListCampaigns campaignStatus(ParameterFiltersListCampaignsCampaignStatus campaignStatus) {
    
    this.campaignStatus = campaignStatus;
    return this;
  }

   /**
   * Get campaignStatus
   * @return campaignStatus
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsCampaignStatus getCampaignStatus() {
    return campaignStatus;
  }


  public void setCampaignStatus(ParameterFiltersListCampaignsCampaignStatus campaignStatus) {
    this.campaignStatus = campaignStatus;
  }


  public ParameterFiltersListCampaigns isReferralCode(ParameterFiltersListCampaignsIsReferralCode isReferralCode) {
    
    this.isReferralCode = isReferralCode;
    return this;
  }

   /**
   * Get isReferralCode
   * @return isReferralCode
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsIsReferralCode getIsReferralCode() {
    return isReferralCode;
  }


  public void setIsReferralCode(ParameterFiltersListCampaignsIsReferralCode isReferralCode) {
    this.isReferralCode = isReferralCode;
  }


  public ParameterFiltersListCampaigns validityTimeframe(ParameterFiltersListCampaignsValidityTimeframe validityTimeframe) {
    
    this.validityTimeframe = validityTimeframe;
    return this;
  }

   /**
   * Get validityTimeframe
   * @return validityTimeframe
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsValidityTimeframe getValidityTimeframe() {
    return validityTimeframe;
  }


  public void setValidityTimeframe(ParameterFiltersListCampaignsValidityTimeframe validityTimeframe) {
    this.validityTimeframe = validityTimeframe;
  }


  public ParameterFiltersListCampaigns voucherType(ParameterFiltersListCampaignsVoucherType voucherType) {
    
    this.voucherType = voucherType;
    return this;
  }

   /**
   * Get voucherType
   * @return voucherType
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsVoucherType getVoucherType() {
    return voucherType;
  }


  public void setVoucherType(ParameterFiltersListCampaignsVoucherType voucherType) {
    this.voucherType = voucherType;
  }


  public ParameterFiltersListCampaigns categories(ParameterFiltersListCampaignsCategories categories) {
    
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsCategories getCategories() {
    return categories;
  }


  public void setCategories(ParameterFiltersListCampaignsCategories categories) {
    this.categories = categories;
  }


  public ParameterFiltersListCampaigns categoryIds(ParameterFiltersListCampaignsCategoryIds categoryIds) {
    
    this.categoryIds = categoryIds;
    return this;
  }

   /**
   * Get categoryIds
   * @return categoryIds
  **/
  @javax.annotation.Nullable
  public ParameterFiltersListCampaignsCategoryIds getCategoryIds() {
    return categoryIds;
  }


  public void setCategoryIds(ParameterFiltersListCampaignsCategoryIds categoryIds) {
    this.categoryIds = categoryIds;
  }


  public ParameterFiltersListCampaigns junction(Junction junction) {
    
    this.junction = junction;
    return this;
  }

   /**
   * Get junction
   * @return junction
  **/
  @javax.annotation.Nullable
  public Junction getJunction() {
    return junction;
  }


  public void setJunction(Junction junction) {
    this.junction = junction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterFiltersListCampaigns parameterFiltersListCampaigns = (ParameterFiltersListCampaigns) o;
    return Objects.equals(this.campaignStatus, parameterFiltersListCampaigns.campaignStatus) &&
        Objects.equals(this.isReferralCode, parameterFiltersListCampaigns.isReferralCode) &&
        Objects.equals(this.validityTimeframe, parameterFiltersListCampaigns.validityTimeframe) &&
        Objects.equals(this.voucherType, parameterFiltersListCampaigns.voucherType) &&
        Objects.equals(this.categories, parameterFiltersListCampaigns.categories) &&
        Objects.equals(this.categoryIds, parameterFiltersListCampaigns.categoryIds) &&
        Objects.equals(this.junction, parameterFiltersListCampaigns.junction);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignStatus, isReferralCode, validityTimeframe, voucherType, categories, categoryIds, junction);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterFiltersListCampaigns {\n");
    sb.append("    campaignStatus: ").append(toIndentedString(campaignStatus)).append("\n");
    sb.append("    isReferralCode: ").append(toIndentedString(isReferralCode)).append("\n");
    sb.append("    validityTimeframe: ").append(toIndentedString(validityTimeframe)).append("\n");
    sb.append("    voucherType: ").append(toIndentedString(voucherType)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    categoryIds: ").append(toIndentedString(categoryIds)).append("\n");
    sb.append("    junction: ").append(toIndentedString(junction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("campaign_status");
    openapiFields.add("is_referral_code");
    openapiFields.add("validity_timeframe");
    openapiFields.add("voucher_type");
    openapiFields.add("categories");
    openapiFields.add("category_ids");
    openapiFields.add("junction");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ParameterFiltersListCampaigns.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ParameterFiltersListCampaigns' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ParameterFiltersListCampaigns> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ParameterFiltersListCampaigns.class));

       return (TypeAdapter<T>) new TypeAdapter<ParameterFiltersListCampaigns>() {
           @Override
           public void write(JsonWriter out, ParameterFiltersListCampaigns value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ParameterFiltersListCampaigns read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ParameterFiltersListCampaigns given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ParameterFiltersListCampaigns
  * @throws IOException if the JSON string is invalid with respect to ParameterFiltersListCampaigns
  */
  public static ParameterFiltersListCampaigns fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ParameterFiltersListCampaigns.class);
  }

 /**
  * Convert an instance of ParameterFiltersListCampaigns to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

